# Generated automatically from Makefile.in by configure.
#
# This is a Gromacs 3.0 template makefile for your own utility programs.
#
# Copy this file to whatever directory you are using for your own
# software and add more targets like the template one below.
#
# If you are using gmake it is relatively straightforward to add
# an include based on environment variables (like previous Gromacs versions)
# to select compiler flags and stuff automatically, but below it is static:
#

# Variables set by the configuration script:
LIBS         = -lmd_mpi -lgmx_mpi -lnsl -lfftw3f   
LDFLAGS      = -L/home/alarcj/gromacs_stampede/exe/gromacs-4.0.7_flatbottom/exec/lib -L/home/alarcj/gromacs_stampede/exe/gromacs-4.0.7_flatbottom/../fftw-3.3.3_sse2/exec/lib  
CFLAGS	     = -O3 -tpp7 -axW -ip -w -funroll-all-loops  -I/home/alarcj/gromacs_stampede/exe/gromacs-4.0.7_flatbottom/exec/include -I/home/alarcj/gromacs_stampede/exe/gromacs-4.0.7_flatbottom/exec/include/gromacs	
CC           = mpicc
LD           = $(CC)

# The real make targets - note that most make programs support
# the shortcut $^ instead of listing all object files a second
# time, but we cannot count on it...

template:	template.o
		$(LD) $(LDFLAGS) -o $@ template.o $(LIBS)
